{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: server.custom-domain
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingressClassName: nginx
  rules:
    {{- range $index, $host := .Values.ingress.hosts }}
    - host: {{$host}}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "prometheus-proxy.fullname" $ }}
                port:
                  number: 8000
    {{- end }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . | quote}}
      {{- end }}
      secretName: {{.Values.ingress.certSecretName | quote }}

{{- end }}
