# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/equinor/radix/prometheus-proxy
  tag: ""
  pullPolicy: Always

# Annotations to add to the Deployment
deploymentAnnotations: {}
# Extra pod labels
podLabels: {}

# Logging
logLevel: info
logPretty: "False"
prometheusUrl: ""

ingress:
  enabled: true
  hosts: []
  annotations: {}
  certSecretName: "prometheus-proxy-tls-cert"

route:
  main:
    # -- Enables or disables the route
    enabled: false

    # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
    apiVersion: gateway.networking.k8s.io/v1
    # -- Set the route kind
    # Valid options are GRPCRoute, HTTPRoute, TCPRoute, TLSRoute, UDPRoute
    kind: HTTPRoute

    annotations: {}
    labels: {}

    hostnames: []
    # - my-filter.example.com
    parentRefs: []
    # - name: acme-gw

    matches:
      - path:
          type: PathPrefix
          value: /

    ## Timeouts define the timeouts that can be configured for an HTTP request.
    ## Ref. https://gateway-api.sigs.k8s.io/api-types/httproute/#timeouts-optional
    timeouts: {}
    # request: 10s
    # backendRequest: 5s

    ## Filters define the filters that are applied to requests that match this rule.
    filters: []

    ## Additional custom rules that can be added to the route
    additionalRules: []

    ## httpsRedirect adds a filter for redirecting to https (HTTP 301 Moved Permanently).
    ## To redirect HTTP traffic to HTTPS, you need to have a Gateway with both HTTP and HTTPS listeners.
    ## Matches and filters do not take effect if enabled.
    ## Ref. https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/
    httpsRedirect: false

resources:
  limits:
    cpu: 50m
    memory: 20Mi
  requests:
    cpu: 50m
    memory: 20Mi

# Affinity for pod scheduling
affinity: {}

# Node selector for pod scheduling
nodeSelector: {}

# Tolerations for pod scheduling
tolerations: []
