apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-proxy.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    {{- include "prometheus-proxy.selectorLabels" . | nindent 6 }}
  ports:
    - name: http
      port: 8000
