on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          skip-github-pull-request: true

      # Docker build
      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: ${{ steps.release.outputs.release_created == 'true' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          TAG: ${{ steps.release.outputs.version }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.TAG}}"
          platforms: |
            linux/amd64
            linux/arm64

      # Helm Chart
      - name: Configure Git
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        if: ${{ steps.release.outputs.release_created == 'true' }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
