on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      version: "${{steps.release.outputs.version }}"
      release_created: "${{steps.release.outputs.release_created == 'true' }}"

    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
      - run: echo "${{toJSON(steps.release.outputs.version)}}"
      - run: echo "${{toJSON(steps.release.outputs.release_created)}}"
      - run: echo "${{toJSON(steps.release.outputs.tag_name)}}"

  release-container:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      TAG: ${{ needs.release-please.outputs.version }}
    steps:
      - run: echo "${{needs.release-please.outputs.version}}"
      - run: echo "${{needs.release-please.outputs.release_created}}"
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.TAG}}"
          platforms: |
            linux/amd64
            linux/arm64

  release-helm:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
