on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.release.outputs.version }}
      release_created: ${{steps.release.outputs.release_created }}

    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release

  release-container:
    runs-on: ubuntu-latest
    needs: release-please
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      TAG: ${{ needs.release-please.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=${{ env.TAG }}
            type=raw,value=latest-{{date 'YYYYMMDDHHmmss'}}-{{sha}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release-helm:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{needs.release-please.outputs.release_created == 'true'}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important parameter

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
